"""create inventory check tables

Revision ID: bcb2fe9c6d53
Revises: f1958de3a05b
Create Date: 2026-09-12 15:28:59.520270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcb2fe9c6d53"
down_revision: str | Sequence[str] | None = "f1958de3a05b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("check_no", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("check_date", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("adjustment_transaction_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("check_no"),
    )
    op.create_table(
        "inventory_check_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inventory_check_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("system_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("actual_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("difference", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["inventory_check_id"], ["inventory_checks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inventory_check_id",
            "material_id",
            name="uq_inventory_check_details_check_material",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory_check_details")
    op.drop_table("inventory_checks")
    # ### end Alembic commands ###
